version: '3.8'

services:
  geth:
    image: ethereum/client-go:stable
    volumes:
      - ./data:/root/.ethereum
    ports:
      - "30303:30303"
      - "8545:8545"
      - "8546:8546"
    command: >
      geth --http --http.addr "0.0.0.0" --http.port 8545 --http.api "eth,net,web3" 
      --ws --ws.addr "0.0.0.0" --ws.port 8546 --ws.api "eth,net,web3" --syncmode "full" --networkid 17000
