version: '3.8'
services:
  prysm-beacon:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    volumes:
      - ./prysm_beacon_data:/data
    command: >
      --datadir=/data 
      --http-web3provider=http://geth:8545
      --p2p-host-ip=${P2P_HOST_IP}
      --p2p-host-dns=${P2P_HOST_DNS}
    environment:
      - P2P_HOST_IP=${P2P_HOST_IP}
      - P2P_HOST_DNS=${P2P_HOST_DNS}
    ports:
      - 4000:4000
      - 13000:13000
    restart: unless-stopped

  prysm-validator:
    image: gcr.io/prysmaticlabs/prysm/validator:stable
    volumes:
      - ./prysm_validator_data:/data
      - ./keystore:/keystore
      - ./validator_passwords:/passwords
    command: >
      --datadir=/data
      --beacon-rpc-provider=prysm-beacon:4000
      --wallet-dir=/keystore
      --wallet-password-file=/passwords/wallet_password.txt
    depends_on:
      - prysm-beacon
    restart: unless-stopped
